# Generated by Django 5.0.4 on 2024-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMX_R_025_SCFI_2015', '0003_giro_logeval_sector_sector_productivo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(choices=[('PU', 'Público'), ('PR', 'Privado'), ('SO', 'Social')], max_length=7),
        ),
    ]
