# Generated by Django 5.0.4 on 2024-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMX_R_025_SCFI_2015', '0004_sector_id_alter_sector_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('SOCIAL', 'Social')], max_length=7),
        ),
    ]
