# Generated by Django 5.0.4 on 2024-05-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMX_R_025_SCFI_2015', '0006_asesor_certificador_tipo_certificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multisitio',
            old_name='id_domicilio',
            new_name='id_domicilio_empresa',
        ),
    ]
